// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  colored_text_block: dynamic(() => import('./ColoredTextBlock')),
  contact_form: dynamic(() => import('./ContactForm')),
  contact_info: dynamic(() => import('./ContactInfo')),
  copyright: dynamic(() => import('./Copyright')),
  gallery_carousel: dynamic(() => import('./GalleryCarousel')),
  icon_bar: dynamic(() => import('./IconBar')),
  image_block: dynamic(() => import('./ImageBlock')),
  image_with_text: dynamic(() => import('./ImageWithText')),
  map: dynamic(() => import('./Map')),
  navigation: dynamic(() => import('./Navigation')),
  price_list: dynamic(() => import('./PriceList')),
  promo_cards: dynamic(() => import('./PromoCards')),
  promo_panel: dynamic(() => import('./PromoPanel')),
  reviews_carousel: dynamic(() => import('./ReviewsCarousel')),
  rich_text: dynamic(() => import('./RichText')),
};
