// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  image_block: dynamic(() => import('./ImageBlock')),
  news_panel: dynamic(() => import('./NewsPanel')),
  promo_panel: dynamic(() => import('./PromoPanel')),
  rich_text: dynamic(() => import('./RichText')),
};
